flyway.url=jdbc:postgresql://postgres:5432/jly
flyway.user=jly_admin
flyway.password=localdevpassword
flyway.schemas=core,membership,public
flyway.defaultSchema=public
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
